name: s3
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0-97.0.dev

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: any
  flashy_flushbar: any

  minio: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: JetBrainsMono
      fonts:
        - asset : assets/fonts/JetBrainsMono.ttf

  assets:
    - assets/translations/
