name: s3
description: "Cross platform client for S3-compatible storage"
publish_to: 'none' 

version: 1.1.1+111

environment:
  sdk: ^3.9.0-97.0.dev

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: any
  flashy_flushbar: any

  minio: any
  file_picker: any
  file_saver: any
  path_provider: any
  pdfrx: any
  video_player: any

dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #     dart run flutter_launcher_icons
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts: 
    - family: JetBrainsMono
      fonts:
        - asset : assets/fonts/JetBrainsMono.ttf

  assets:
    - assets/translations/
